# Use root/example as user/password credentials
version: '3.1'

services:
  reporter:
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - IP_ADDR=0.0.0.0
      - PORT=8080
      - MONGO_USER=root
      - MONGO_PASS=example
      - MONGO_IP=mongo
      - MONGO_PORT=27017
      - SECRET_KEY=1234
      - DATABASE=reporter
    depends_on:
      - mongo
    networks:
      - reporternet
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: reporter
    networks:
      - reporternet

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - reporternet

networks:
  reporternet:
    driver: bridge