apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-mongo-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-mongo-reporter
  template:
    metadata:
      labels:
        app: go-mongo-reporter 
    spec:
      initContainers:
      - name: go-mongo-reporter-migrations
        image: kaerhae/go-mongo-reporter-migration
        imagePullPolicy: IfNotPresent
        command: ["./bin/migrate", "up"]
        envFrom:
        - secretRef:
            name: reporter-secrets
      containers:
      - name: reporter
        image: kaerhae/go-mongo-reporter 
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8080"
        envFrom:
        - secretRef:
            name: reporter-secrets
        ports:
          - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10